### ISSUE TITLE
Inconsistent values of @gender

### ISSUE THREAD

**Issue by djbpitt** [scanney/Grimm-Fairytales#6]
The schema allows any text as the value of the `@gender` attribute, and the values in the corpus are incorrect or inconsistent in some places: "male", "female", "feamle" (sic), "fenale" (sic), "mixed", "male | female", "female | male", "neutral", "positive". Refactor the `@gender` declaration to an or-group of strings or a list?

**Comment by sea089** [comment]
I went back in and fixed the schema so that the attribute values are more clearly defined! The new schema has been pushed to GitHub.
